//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondFloor.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecondFloor.I18N.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Registration.
        /// </summary>
        public static string AnuncianteController_HttpGet_Cadastro_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Cadastro_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Registration.
        /// </summary>
        public static string AnuncianteController_HttpGet_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the following Seller?.
        /// </summary>
        public static string AnuncianteController_HttpGet_Delete_Action_ViewBagMessage {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Delete_Action_ViewBagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Seller.
        /// </summary>
        public static string AnuncianteController_HttpGet_Delete_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Delete_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Detail.
        /// </summary>
        public static string AnuncianteController_HttpGet_Detail_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Detail_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Detail.
        /// </summary>
        public static string AnuncianteController_HttpGet_Detalhes_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Detalhes_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Seller.
        /// </summary>
        public static string AnuncianteController_HttpGet_Edit_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Edit_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellers List.
        /// </summary>
        public static string AnuncianteController_HttpGet_List_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_List_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellers List.
        /// </summary>
        public static string AnuncianteController_HttpGet_Listar_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Listar_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Registration.
        /// </summary>
        public static string AnuncianteController_HttpPost_Cadastro_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Cadastro_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellers List.
        /// </summary>
        public static string AnuncianteController_HttpPost_Cadastro_Action_ViewBagTitle_Adm {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Cadastro_Action_ViewBagTitle_Adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Registration.
        /// </summary>
        public static string AnuncianteController_HttpPost_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Seller.
        /// </summary>
        public static string AnuncianteController_HttpPost_Delete_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Delete_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Seller.
        /// </summary>
        public static string AnuncianteController_HttpPost_Edit_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Edit_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cnpj.
        /// </summary>
        public static string AnuncianteViewModels_AttributeName_CNPJ {
            get {
                return ResourceManager.GetString("AnuncianteViewModels_AttributeName_CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string AnuncianteViewModels_AttributeName_Email {
            get {
                return ResourceManager.GetString("AnuncianteViewModels_AttributeName_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string AnuncianteViewModels_AttributeName_RazaoSocial {
            get {
                return ResourceManager.GetString("AnuncianteViewModels_AttributeName_RazaoSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string AnuncianteViewModels_AttributeName_Responsavel {
            get {
                return ResourceManager.GetString("AnuncianteViewModels_AttributeName_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language:.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string View_Anunciante_AnunciantePartialView_Botao_Cancelar {
            get {
                return ResourceManager.GetString("View_Anunciante_AnunciantePartialView_Botao_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string View_Anunciante_AnunciantePartialView_Botao_Salvar {
            get {
                return ResourceManager.GetString("View_Anunciante_AnunciantePartialView_Botao_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string View_Anunciante_Cadastro_Botao_Salvar {
            get {
                return ResourceManager.GetString("View_Anunciante_Cadastro_Botao_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Seller.
        /// </summary>
        public static string View_Anunciante_ListaAnunciantePartialView_Botao_NovoAnunciante {
            get {
                return ResourceManager.GetString("View_Anunciante_ListaAnunciantePartialView_Botao_NovoAnunciante", resourceCulture);
            }
        }
    }
}
