//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondFloor.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecondFloor.I18N.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Registration.
        /// </summary>
        public static string AnuncianteController_HttpGet_Cadastro_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Cadastro_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Registration.
        /// </summary>
        public static string AnuncianteController_HttpGet_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the following Seller? Are you sure?.
        /// </summary>
        public static string AnuncianteController_HttpGet_Delete_Action_ViewBagMessage {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Delete_Action_ViewBagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Seller.
        /// </summary>
        public static string AnuncianteController_HttpGet_Delete_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Delete_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Detail.
        /// </summary>
        public static string AnuncianteController_HttpGet_Detail_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Detail_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Detail.
        /// </summary>
        public static string AnuncianteController_HttpGet_Detalhes_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Detalhes_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Seller.
        /// </summary>
        public static string AnuncianteController_HttpGet_Edit_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Edit_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellers List.
        /// </summary>
        public static string AnuncianteController_HttpGet_List_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_List_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellers List.
        /// </summary>
        public static string AnuncianteController_HttpGet_Listar_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Listar_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Registration.
        /// </summary>
        public static string AnuncianteController_HttpPost_Cadastro_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Cadastro_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellers List.
        /// </summary>
        public static string AnuncianteController_HttpPost_Cadastro_Action_ViewBagTitle_Adm {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Cadastro_Action_ViewBagTitle_Adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Registration.
        /// </summary>
        public static string AnuncianteController_HttpPost_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Seller.
        /// </summary>
        public static string AnuncianteController_HttpPost_Delete_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Delete_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Seller.
        /// </summary>
        public static string AnuncianteController_HttpPost_Edit_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Edit_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cnpj.
        /// </summary>
        public static string AnuncianteViewModels_AttributeName_CNPJ {
            get {
                return ResourceManager.GetString("AnuncianteViewModels_AttributeName_CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string AnuncianteViewModels_AttributeName_Email {
            get {
                return ResourceManager.GetString("AnuncianteViewModels_AttributeName_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string AnuncianteViewModels_AttributeName_RazaoSocial {
            get {
                return ResourceManager.GetString("AnuncianteViewModels_AttributeName_RazaoSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string AnuncianteViewModels_AttributeName_Responsavel {
            get {
                return ResourceManager.GetString("AnuncianteViewModels_AttributeName_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        public static string EnderecoController_HttpGet_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("EnderecoController_HttpGet_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the following Address? Are you sure?.
        /// </summary>
        public static string EnderecoController_HttpGet_Delete_Action_ViewBagMessage {
            get {
                return ResourceManager.GetString("EnderecoController_HttpGet_Delete_Action_ViewBagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Address.
        /// </summary>
        public static string EnderecoController_HttpGet_Delete_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("EnderecoController_HttpGet_Delete_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Address.
        /// </summary>
        public static string EnderecoController_HttpGet_Edit_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("EnderecoController_HttpGet_Edit_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address List.
        /// </summary>
        public static string EnderecoController_HttpGet_List_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("EnderecoController_HttpGet_List_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        public static string EnderecoController_HttpPost_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("EnderecoController_HttpPost_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Address.
        /// </summary>
        public static string EnderecoController_HttpPost_Delete_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("EnderecoController_HttpPost_Delete_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Address.
        /// </summary>
        public static string EnderecoController_HttpPost_Edit_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("EnderecoController_HttpPost_Edit_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village.
        /// </summary>
        public static string EnderecoViewModels_AttributeName_Bairro {
            get {
                return ResourceManager.GetString("EnderecoViewModels_AttributeName_Bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string EnderecoViewModels_AttributeName_Cep {
            get {
                return ResourceManager.GetString("EnderecoViewModels_AttributeName_Cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string EnderecoViewModels_AttributeName_Cidade {
            get {
                return ResourceManager.GetString("EnderecoViewModels_AttributeName_Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complement.
        /// </summary>
        public static string EnderecoViewModels_AttributeName_Complemento {
            get {
                return ResourceManager.GetString("EnderecoViewModels_AttributeName_Complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string EnderecoViewModels_AttributeName_Estado {
            get {
                return ResourceManager.GetString("EnderecoViewModels_AttributeName_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string EnderecoViewModels_AttributeName_Logradouro {
            get {
                return ResourceManager.GetString("EnderecoViewModels_AttributeName_Logradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string EnderecoViewModels_AttributeName_Numero {
            get {
                return ResourceManager.GetString("EnderecoViewModels_AttributeName_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string ProdutoController_HttpGet_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("ProdutoController_HttpGet_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the following Product? Are you sure?.
        /// </summary>
        public static string ProdutoController_HttpGet_Delete_Action_ViewBagMessage {
            get {
                return ResourceManager.GetString("ProdutoController_HttpGet_Delete_Action_ViewBagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product.
        /// </summary>
        public static string ProdutoController_HttpGet_Delete_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("ProdutoController_HttpGet_Delete_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string ProdutoController_HttpGet_Edit_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("ProdutoController_HttpGet_Edit_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product List.
        /// </summary>
        public static string ProdutoController_HttpGet_List_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("ProdutoController_HttpGet_List_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string ProdutoController_HttpPost_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("ProdutoController_HttpPost_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product.
        /// </summary>
        public static string ProdutoController_HttpPost_Delete_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("ProdutoController_HttpPost_Delete_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string ProdutoController_HttpPost_Edit_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("ProdutoController_HttpPost_Edit_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProdutoViewModels_AttributeName_Descricao {
            get {
                return ResourceManager.GetString("ProdutoViewModels_AttributeName_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture.
        /// </summary>
        public static string ProdutoViewModels_AttributeName_Fabricante {
            get {
                return ResourceManager.GetString("ProdutoViewModels_AttributeName_Fabricante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product / Services.
        /// </summary>
        public static string ProdutoViewModels_AttributeName_NomeProduto {
            get {
                return ResourceManager.GetString("ProdutoViewModels_AttributeName_NomeProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string ProdutoViewModels_AttributeName_Referencia {
            get {
                return ResourceManager.GetString("ProdutoViewModels_AttributeName_Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string ProdutoViewModels_AttributeName_Valor {
            get {
                return ResourceManager.GetString("ProdutoViewModels_AttributeName_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language:.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string View_Anunciante_AnunciantePartialView_Botao_Cancelar {
            get {
                return ResourceManager.GetString("View_Anunciante_AnunciantePartialView_Botao_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string View_Anunciante_AnunciantePartialView_Botao_Salvar {
            get {
                return ResourceManager.GetString("View_Anunciante_AnunciantePartialView_Botao_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string View_Anunciante_Cadastro_Botao_Salvar {
            get {
                return ResourceManager.GetString("View_Anunciante_Cadastro_Botao_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Seller.
        /// </summary>
        public static string View_Anunciante_ListaAnunciantePartialView_Botao_NovoAnunciante {
            get {
                return ResourceManager.GetString("View_Anunciante_ListaAnunciantePartialView_Botao_NovoAnunciante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string View_Endereco_EnderecoPartialView_Botao_Cancelar {
            get {
                return ResourceManager.GetString("View_Endereco_EnderecoPartialView_Botao_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string View_Endereco_EnderecoPartialView_Botao_Salvar {
            get {
                return ResourceManager.GetString("View_Endereco_EnderecoPartialView_Botao_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        public static string View_Endereco_ListaEnderecoPartialView_Botao_NovoEndereco {
            get {
                return ResourceManager.GetString("View_Endereco_ListaEnderecoPartialView_Botao_NovoEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string View_Produto_ListaProdutoPartialView_Botao_NovoProduto {
            get {
                return ResourceManager.GetString("View_Produto_ListaProdutoPartialView_Botao_NovoProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string View_Produto_ProdutoPartialView_Botao_Cancelar {
            get {
                return ResourceManager.GetString("View_Produto_ProdutoPartialView_Botao_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string View_Produto_ProdutoPartialView_Botao_Salvar {
            get {
                return ResourceManager.GetString("View_Produto_ProdutoPartialView_Botao_Salvar", resourceCulture);
            }
        }
    }
}
