//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondFloor.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecondFloor.I18n.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Registration.
        /// </summary>
        public static string AnuncianteController_HttpGet_Cadastro_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Cadastro_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Registration.
        /// </summary>
        public static string AnuncianteController_HttpGet_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the following Seller? Are you sure?.
        /// </summary>
        public static string AnuncianteController_HttpGet_Delete_Action_ViewBagMessage {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Delete_Action_ViewBagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Seller.
        /// </summary>
        public static string AnuncianteController_HttpGet_Delete_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Delete_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Detail.
        /// </summary>
        public static string AnuncianteController_HttpGet_Detail_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Detail_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Detail.
        /// </summary>
        public static string AnuncianteController_HttpGet_Detalhes_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Detalhes_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Seller.
        /// </summary>
        public static string AnuncianteController_HttpGet_Edit_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Edit_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellers List.
        /// </summary>
        public static string AnuncianteController_HttpGet_List_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_List_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellers List.
        /// </summary>
        public static string AnuncianteController_HttpGet_Listar_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpGet_Listar_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Registration.
        /// </summary>
        public static string AnuncianteController_HttpPost_Cadastro_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Cadastro_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellers List.
        /// </summary>
        public static string AnuncianteController_HttpPost_Cadastro_Action_ViewBagTitle_Adm {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Cadastro_Action_ViewBagTitle_Adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Registration.
        /// </summary>
        public static string AnuncianteController_HttpPost_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Seller.
        /// </summary>
        public static string AnuncianteController_HttpPost_Delete_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Delete_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Seller.
        /// </summary>
        public static string AnuncianteController_HttpPost_Edit_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncianteController_HttpPost_Edit_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string AnuncianteServices_AlterarAnunciante_Error {
            get {
                return ResourceManager.GetString("AnuncianteServices_AlterarAnunciante_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller not found!.
        /// </summary>
        public static string AnuncianteServices_AlterarAnunciante_NotFound {
            get {
                return ResourceManager.GetString("AnuncianteServices_AlterarAnunciante_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller updated successfully!.
        /// </summary>
        public static string AnuncianteServices_AlterarAnunciante_Success {
            get {
                return ResourceManager.GetString("AnuncianteServices_AlterarAnunciante_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string AnuncianteServices_CadastrarAnunciante_Error {
            get {
                return ResourceManager.GetString("AnuncianteServices_CadastrarAnunciante_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller registred successfully!.
        /// </summary>
        public static string AnuncianteServices_CadastrarAnunciante_Success {
            get {
                return ResourceManager.GetString("AnuncianteServices_CadastrarAnunciante_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string AnuncianteServices_EncontrarAnunciantePor_Error {
            get {
                return ResourceManager.GetString("AnuncianteServices_EncontrarAnunciantePor_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller not found!.
        /// </summary>
        public static string AnuncianteServices_EncontrarAnunciantePor_NotFound {
            get {
                return ResourceManager.GetString("AnuncianteServices_EncontrarAnunciantePor_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Found!.
        /// </summary>
        public static string AnuncianteServices_EncontrarAnunciantePor_Scuccess {
            get {
                return ResourceManager.GetString("AnuncianteServices_EncontrarAnunciantePor_Scuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string AnuncianteServices_EncontrarTodosAnunciantes_Error {
            get {
                return ResourceManager.GetString("AnuncianteServices_EncontrarTodosAnunciantes_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller not found!.
        /// </summary>
        public static string AnuncianteServices_EncontrarTodosAnunciantes_NotFound {
            get {
                return ResourceManager.GetString("AnuncianteServices_EncontrarTodosAnunciantes_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} sellers.
        /// </summary>
        public static string AnuncianteServices_EncontrarTodosAnunciantes_Success {
            get {
                return ResourceManager.GetString("AnuncianteServices_EncontrarTodosAnunciantes_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cnpj.
        /// </summary>
        public static string AnuncianteViewModels_AttributeName_CNPJ {
            get {
                return ResourceManager.GetString("AnuncianteViewModels_AttributeName_CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string AnuncianteViewModels_AttributeName_Email {
            get {
                return ResourceManager.GetString("AnuncianteViewModels_AttributeName_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string AnuncianteViewModels_AttributeName_RazaoSocial {
            get {
                return ResourceManager.GetString("AnuncianteViewModels_AttributeName_RazaoSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string AnuncianteViewModels_AttributeName_Responsavel {
            get {
                return ResourceManager.GetString("AnuncianteViewModels_AttributeName_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Advertising.
        /// </summary>
        public static string AnuncioController_HttpGet_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncioController_HttpGet_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising List.
        /// </summary>
        public static string AnuncioController_HttpGet_List_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncioController_HttpGet_List_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Advertising.
        /// </summary>
        public static string AnuncioController_HttpPost_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("AnuncioController_HttpPost_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string AnuncioService_AlterarAnuncio_Error {
            get {
                return ResourceManager.GetString("AnuncioService_AlterarAnuncio_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising not found!.
        /// </summary>
        public static string AnuncioService_AlterarAnuncio_NotFound {
            get {
                return ResourceManager.GetString("AnuncioService_AlterarAnuncio_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising updated successfully!.
        /// </summary>
        public static string AnuncioService_AlterarAnuncio_Success {
            get {
                return ResourceManager.GetString("AnuncioService_AlterarAnuncio_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string AnuncioService_CadastrarAnuncio_Error {
            get {
                return ResourceManager.GetString("AnuncioService_CadastrarAnuncio_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller not found!.
        /// </summary>
        public static string AnuncioService_CadastrarAnuncio_NotFound {
            get {
                return ResourceManager.GetString("AnuncioService_CadastrarAnuncio_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising registred successfully..
        /// </summary>
        public static string AnuncioService_CadastrarAnuncio_Success {
            get {
                return ResourceManager.GetString("AnuncioService_CadastrarAnuncio_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string AnuncioService_EncontrarAnuncioPor_Error {
            get {
                return ResourceManager.GetString("AnuncioService_EncontrarAnuncioPor_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising not found!.
        /// </summary>
        public static string AnuncioService_EncontrarAnuncioPor_NotFound {
            get {
                return ResourceManager.GetString("AnuncioService_EncontrarAnuncioPor_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising found!.
        /// </summary>
        public static string AnuncioService_EncontrarAnuncioPor_Success {
            get {
                return ResourceManager.GetString("AnuncioService_EncontrarAnuncioPor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string AnuncioService_EncontrarTodosAnuncios_Error {
            get {
                return ResourceManager.GetString("AnuncioService_EncontrarTodosAnuncios_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller information not found!.
        /// </summary>
        public static string AnuncioService_EncontrarTodosAnuncios_NotFound {
            get {
                return ResourceManager.GetString("AnuncioService_EncontrarTodosAnuncios_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} seller(s)..
        /// </summary>
        public static string AnuncioService_EncontrarTodosAnuncios_Success {
            get {
                return ResourceManager.GetString("AnuncioService_EncontrarTodosAnuncios_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string AnuncioService_EnviarAnuncioParaPublicacao_Error {
            get {
                return ResourceManager.GetString("AnuncioService_EnviarAnuncioParaPublicacao_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No listing found!.
        /// </summary>
        public static string AnuncioService_EnviarAnuncioParaPublicacao_NotFound {
            get {
                return ResourceManager.GetString("AnuncioService_EnviarAnuncioParaPublicacao_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising sent for publishing successfully.
        /// </summary>
        public static string AnuncioService_EnviarAnuncioParaPublicacao_Success {
            get {
                return ResourceManager.GetString("AnuncioService_EnviarAnuncioParaPublicacao_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string AnuncioService_ExcluirAnuncio_Error {
            get {
                return ResourceManager.GetString("AnuncioService_ExcluirAnuncio_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising not found!.
        /// </summary>
        public static string AnuncioService_ExcluirAnuncio_NotFound {
            get {
                return ResourceManager.GetString("AnuncioService_ExcluirAnuncio_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising deleted successfully.
        /// </summary>
        public static string AnuncioService_ExcluirAnuncio_Success {
            get {
                return ResourceManager.GetString("AnuncioService_ExcluirAnuncio_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string AnuncioService_PublicarAnuncio_Error {
            get {
                return ResourceManager.GetString("AnuncioService_PublicarAnuncio_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No listing found!.
        /// </summary>
        public static string AnuncioService_PublicarAnuncio_NotFound {
            get {
                return ResourceManager.GetString("AnuncioService_PublicarAnuncio_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising published successfully.
        /// </summary>
        public static string AnuncioService_PublicarAnuncio_Success {
            get {
                return ResourceManager.GetString("AnuncioService_PublicarAnuncio_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string AnuncioViewModel_AttributeName_DataFim {
            get {
                return ResourceManager.GetString("AnuncioViewModel_AttributeName_DataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string AnuncioViewModel_AttributeName_DataInicio {
            get {
                return ResourceManager.GetString("AnuncioViewModel_AttributeName_DataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string AnuncioViewModel_AttributeName_Enderecos {
            get {
                return ResourceManager.GetString("AnuncioViewModel_AttributeName_Enderecos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string AnuncioViewModel_AttributeName_Ofertas {
            get {
                return ResourceManager.GetString("AnuncioViewModel_AttributeName_Ofertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AnuncioViewModel_AttributeName_Status {
            get {
                return ResourceManager.GetString("AnuncioViewModel_AttributeName_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string AnuncioViewModel_AttributeName_Titulo {
            get {
                return ResourceManager.GetString("AnuncioViewModel_AttributeName_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string ConsumidorServices_AtribuirRatingPara_Error {
            get {
                return ResourceManager.GetString("ConsumidorServices_AtribuirRatingPara_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer not found!.
        /// </summary>
        public static string ConsumidorServices_AtribuirRatingPara_NotFound {
            get {
                return ResourceManager.GetString("ConsumidorServices_AtribuirRatingPara_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating assigned successfully!.
        /// </summary>
        public static string ConsumidorServices_AtribuirRatingPara_Success {
            get {
                return ResourceManager.GetString("ConsumidorServices_AtribuirRatingPara_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string ConsumidorServices_CadastrarConsumidor_Error {
            get {
                return ResourceManager.GetString("ConsumidorServices_CadastrarConsumidor_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer registred successfully.
        /// </summary>
        public static string ConsumidorServices_CadastrarConsumidor_Success {
            get {
                return ResourceManager.GetString("ConsumidorServices_CadastrarConsumidor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string ConsumidorServices_EncontrarOfertaPor_Error {
            get {
                return ResourceManager.GetString("ConsumidorServices_EncontrarOfertaPor_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer not found!.
        /// </summary>
        public static string ConsumidorServices_EncontrarOfertaPor_NotFound {
            get {
                return ResourceManager.GetString("ConsumidorServices_EncontrarOfertaPor_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} offers!.
        /// </summary>
        public static string ConsumidorServices_EncontrarOfertaPor_Success {
            get {
                return ResourceManager.GetString("ConsumidorServices_EncontrarOfertaPor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        public static string EnderecoController_HttpGet_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("EnderecoController_HttpGet_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the following Address? Are you sure?.
        /// </summary>
        public static string EnderecoController_HttpGet_Delete_Action_ViewBagMessage {
            get {
                return ResourceManager.GetString("EnderecoController_HttpGet_Delete_Action_ViewBagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Address.
        /// </summary>
        public static string EnderecoController_HttpGet_Delete_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("EnderecoController_HttpGet_Delete_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Address.
        /// </summary>
        public static string EnderecoController_HttpGet_Edit_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("EnderecoController_HttpGet_Edit_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address List.
        /// </summary>
        public static string EnderecoController_HttpGet_List_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("EnderecoController_HttpGet_List_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        public static string EnderecoController_HttpPost_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("EnderecoController_HttpPost_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Address.
        /// </summary>
        public static string EnderecoController_HttpPost_Delete_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("EnderecoController_HttpPost_Delete_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Address.
        /// </summary>
        public static string EnderecoController_HttpPost_Edit_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("EnderecoController_HttpPost_Edit_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string EnderecoServices_AlterarEndereco_Error {
            get {
                return ResourceManager.GetString("EnderecoServices_AlterarEndereco_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not found!.
        /// </summary>
        public static string EnderecoServices_AlterarEndereco_NotFound {
            get {
                return ResourceManager.GetString("EnderecoServices_AlterarEndereco_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address updated successfully!.
        /// </summary>
        public static string EnderecoServices_AlterarEndereco_Success {
            get {
                return ResourceManager.GetString("EnderecoServices_AlterarEndereco_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller not Found.
        /// </summary>
        public static string EnderecoServices_CadastrarEndereco_AnuncianteNotFound {
            get {
                return ResourceManager.GetString("EnderecoServices_CadastrarEndereco_AnuncianteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string EnderecoServices_CadastrarEndereco_Error {
            get {
                return ResourceManager.GetString("EnderecoServices_CadastrarEndereco_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State not found!.
        /// </summary>
        public static string EnderecoServices_CadastrarEndereco_EstadoNotFound {
            get {
                return ResourceManager.GetString("EnderecoServices_CadastrarEndereco_EstadoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address registred successfully!.
        /// </summary>
        public static string EnderecoServices_CadastrarEndereco_Success {
            get {
                return ResourceManager.GetString("EnderecoServices_CadastrarEndereco_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string EnderecoServices_EncontrarEnderecoPor_Error {
            get {
                return ResourceManager.GetString("EnderecoServices_EncontrarEnderecoPor_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not found!.
        /// </summary>
        public static string EnderecoServices_EncontrarEnderecoPor_NotFound {
            get {
                return ResourceManager.GetString("EnderecoServices_EncontrarEnderecoPor_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Found!.
        /// </summary>
        public static string EnderecoServices_EncontrarEnderecoPor_Success {
            get {
                return ResourceManager.GetString("EnderecoServices_EncontrarEnderecoPor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string EnderecoServices_EncontratTodosEnderecos_Error {
            get {
                return ResourceManager.GetString("EnderecoServices_EncontratTodosEnderecos_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller information not found!.
        /// </summary>
        public static string EnderecoServices_EncontratTodosEnderecos_NotFound {
            get {
                return ResourceManager.GetString("EnderecoServices_EncontratTodosEnderecos_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} sellers.
        /// </summary>
        public static string EnderecoServices_EncontratTodosEnderecos_Success {
            get {
                return ResourceManager.GetString("EnderecoServices_EncontratTodosEnderecos_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string EnderecoServices_ExcluirEndereco_Error {
            get {
                return ResourceManager.GetString("EnderecoServices_ExcluirEndereco_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not found!.
        /// </summary>
        public static string EnderecoServices_ExcluirEndereco_NotFound {
            get {
                return ResourceManager.GetString("EnderecoServices_ExcluirEndereco_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address deleted successfully!.
        /// </summary>
        public static string EnderecoServices_ExcluirEndereco_Success {
            get {
                return ResourceManager.GetString("EnderecoServices_ExcluirEndereco_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village.
        /// </summary>
        public static string EnderecoViewModels_AttributeName_Bairro {
            get {
                return ResourceManager.GetString("EnderecoViewModels_AttributeName_Bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string EnderecoViewModels_AttributeName_Cep {
            get {
                return ResourceManager.GetString("EnderecoViewModels_AttributeName_Cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string EnderecoViewModels_AttributeName_Cidade {
            get {
                return ResourceManager.GetString("EnderecoViewModels_AttributeName_Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complement.
        /// </summary>
        public static string EnderecoViewModels_AttributeName_Complemento {
            get {
                return ResourceManager.GetString("EnderecoViewModels_AttributeName_Complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string EnderecoViewModels_AttributeName_Estado {
            get {
                return ResourceManager.GetString("EnderecoViewModels_AttributeName_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string EnderecoViewModels_AttributeName_Logradouro {
            get {
                return ResourceManager.GetString("EnderecoViewModels_AttributeName_Logradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string EnderecoViewModels_AttributeName_Numero {
            get {
                return ResourceManager.GetString("EnderecoViewModels_AttributeName_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors Found:.
        /// </summary>
        public static string Infrastructure_Model_EntityBase_GetErrorMessages {
            get {
                return ResourceManager.GetString("Infrastructure_Model_EntityBase_GetErrorMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description must have at most (1000) characters..
        /// </summary>
        public static string Model_Rules_Produto_Specification_Descricao_Long {
            get {
                return ResourceManager.GetString("Model_Rules_Produto_Specification_Descricao_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description must be specified.
        /// </summary>
        public static string Model_Rules_Produto_Specification_Descricao_NotNull {
            get {
                return ResourceManager.GetString("Model_Rules_Produto_Specification_Descricao_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name must have at most (150) characters..
        /// </summary>
        public static string Model_Rules_Produto_Specification_NomeProduto_Long {
            get {
                return ResourceManager.GetString("Model_Rules_Produto_Specification_NomeProduto_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name must be specified.
        /// </summary>
        public static string Model_Rules_Produto_Specification_NomeProduto_NotNull {
            get {
                return ResourceManager.GetString("Model_Rules_Produto_Specification_NomeProduto_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CNPJis invalid..
        /// </summary>
        public static string Model_Rules_Specification_Anunciante_Cnpj_Invalid {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Anunciante_Cnpj_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CNPJ cannot be null..
        /// </summary>
        public static string Model_Rules_Specification_Anunciante_Cnpj_NotNull {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Anunciante_Cnpj_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email is invalid..
        /// </summary>
        public static string Model_Rules_Specification_Anunciante_Email_Invalid {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Anunciante_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email of seller must have at most (250) characters..
        /// </summary>
        public static string Model_Rules_Specification_Anunciante_Email_Long {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Anunciante_Email_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email cannot be null..
        /// </summary>
        public static string Model_Rules_Specification_Anunciante_Email_NotNull {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Anunciante_Email_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contact must have at most (250) characters..
        /// </summary>
        public static string Model_Rules_Specification_Anunciante_NomeResponsavel_Long {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Anunciante_NomeResponsavel_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contact Information cannot be null..
        /// </summary>
        public static string Model_Rules_Specification_Anunciante_NomeResponsavel_NotNull {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Anunciante_NomeResponsavel_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contact must have at least  (2) characters..
        /// </summary>
        public static string Model_Rules_Specification_Anunciante_NomeResponsavel_Short {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Anunciante_NomeResponsavel_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company Name myst have at most (250) characters..
        /// </summary>
        public static string Model_Rules_Specification_Anunciante_RazaoSocial_Long {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Anunciante_RazaoSocial_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company Name cannot be null..
        /// </summary>
        public static string Model_Rules_Specification_Anunciante_RazaoSocial_NotNull {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Anunciante_RazaoSocial_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company Name myst have at least (4) characters..
        /// </summary>
        public static string Model_Rules_Specification_Anunciante_RazaoSocial_Short {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Anunciante_RazaoSocial_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email of Customer is invalid..
        /// </summary>
        public static string Model_Rules_Specification_Consumidor_Email_Invalid {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Consumidor_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email of customer must have at most (250) characters..
        /// </summary>
        public static string Model_Rules_Specification_Consumidor_Email_Long {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Consumidor_Email_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email of Customer cannot be null..
        /// </summary>
        public static string Model_Rules_Specification_Consumidor_Email_NotNull {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Consumidor_Email_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name of customer must have at most (50) characters..
        /// </summary>
        public static string Model_Rules_Specification_Consumidor_Nome_Long {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Consumidor_Nome_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name of customer cannot be null.
        /// </summary>
        public static string Model_Rules_Specification_Consumidor_Nome_NotNull {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Consumidor_Nome_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name of customer must have at least (4) characters..
        /// </summary>
        public static string Model_Rules_Specification_Consumidor_Nome_Short {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Consumidor_Nome_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The village must have at most (50) characters..
        /// </summary>
        public static string Model_Rules_Specification_Endereco_Bairro_Long {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Endereco_Bairro_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The village must be specified..
        /// </summary>
        public static string Model_Rules_Specification_Endereco_Bairro_NotNull {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Endereco_Bairro_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ZIP must have at most (9) characters..
        /// </summary>
        public static string Model_Rules_Specification_Endereco_Cep_Long {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Endereco_Cep_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ZIP must be specified..
        /// </summary>
        public static string Model_Rules_Specification_Endereco_Cep_NotNull {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Endereco_Cep_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city must have at most (50) characters..
        /// </summary>
        public static string Model_Rules_Specification_Endereco_Cidade_Long {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Endereco_Cidade_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city must be specified..
        /// </summary>
        public static string Model_Rules_Specification_Endereco_Cidade_NotNull {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Endereco_Cidade_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street address complement must have at most (250) characters..
        /// </summary>
        public static string Model_Rules_Specification_Endereco_Complemento_Long {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Endereco_Complemento_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address must have at most (250) characters..
        /// </summary>
        public static string Model_Rules_Specification_Endereco_Logradouro_Long {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Endereco_Logradouro_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address cannot be null..
        /// </summary>
        public static string Model_Rules_Specification_Endereco_Logradouro_NotNull {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Endereco_Logradouro_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address number must be declared..
        /// </summary>
        public static string Model_Rules_Specification_Endereco_Numero_NotNull {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Endereco_Numero_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User!.
        /// </summary>
        public static string Model_Rules_Specification_Usuario_Id_Invalid {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Usuario_Id_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login cannot be null.
        /// </summary>
        public static string Model_Rules_Specification_Usuario_Login_NotNull {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Usuario_Login_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password cannot be null.
        /// </summary>
        public static string Model_Rules_Specification_Usuario_Password_NotNoll {
            get {
                return ResourceManager.GetString("Model_Rules_Specification_Usuario_Password_NotNoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string ProdutoController_HttpGet_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("ProdutoController_HttpGet_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the following Product? Are you sure?.
        /// </summary>
        public static string ProdutoController_HttpGet_Delete_Action_ViewBagMessage {
            get {
                return ResourceManager.GetString("ProdutoController_HttpGet_Delete_Action_ViewBagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product.
        /// </summary>
        public static string ProdutoController_HttpGet_Delete_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("ProdutoController_HttpGet_Delete_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string ProdutoController_HttpGet_Edit_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("ProdutoController_HttpGet_Edit_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product List.
        /// </summary>
        public static string ProdutoController_HttpGet_List_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("ProdutoController_HttpGet_List_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string ProdutoController_HttpPost_Create_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("ProdutoController_HttpPost_Create_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product.
        /// </summary>
        public static string ProdutoController_HttpPost_Delete_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("ProdutoController_HttpPost_Delete_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string ProdutoController_HttpPost_Edit_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("ProdutoController_HttpPost_Edit_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string ProdutoServices_AlterarProduto_Error {
            get {
                return ResourceManager.GetString("ProdutoServices_AlterarProduto_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found!.
        /// </summary>
        public static string ProdutoServices_AlterarProduto_NotFound {
            get {
                return ResourceManager.GetString("ProdutoServices_AlterarProduto_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product updated successfully.
        /// </summary>
        public static string ProdutoServices_AlterarProduto_Success {
            get {
                return ResourceManager.GetString("ProdutoServices_AlterarProduto_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller not found!.
        /// </summary>
        public static string ProdutoServices_CadastrarProduto_Anunciante_NotFound {
            get {
                return ResourceManager.GetString("ProdutoServices_CadastrarProduto_Anunciante_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string ProdutoServices_CadastrarProduto_Error {
            get {
                return ResourceManager.GetString("ProdutoServices_CadastrarProduto_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product registred Successfully .
        /// </summary>
        public static string ProdutoServices_CadastrarProduto_Success {
            get {
                return ResourceManager.GetString("ProdutoServices_CadastrarProduto_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string ProdutoServices_EncontrarProdutoPor_Error {
            get {
                return ResourceManager.GetString("ProdutoServices_EncontrarProdutoPor_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found!.
        /// </summary>
        public static string ProdutoServices_EncontrarProdutoPor_NotFound {
            get {
                return ResourceManager.GetString("ProdutoServices_EncontrarProdutoPor_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produt found!.
        /// </summary>
        public static string ProdutoServices_EncontrarProdutoPor_Success {
            get {
                return ResourceManager.GetString("ProdutoServices_EncontrarProdutoPor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string ProdutoServices_EncontrarTodosProdutos_Error {
            get {
                return ResourceManager.GetString("ProdutoServices_EncontrarTodosProdutos_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller not found!.
        /// </summary>
        public static string ProdutoServices_EncontrarTodosProdutos_NotFound {
            get {
                return ResourceManager.GetString("ProdutoServices_EncontrarTodosProdutos_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} Products!.
        /// </summary>
        public static string ProdutoServices_EncontrarTodosProdutos_Success {
            get {
                return ResourceManager.GetString("ProdutoServices_EncontrarTodosProdutos_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string ProdutoServices_ExcluirProduto_Error {
            get {
                return ResourceManager.GetString("ProdutoServices_ExcluirProduto_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found!.
        /// </summary>
        public static string ProdutoServices_ExcluirProduto_NotFound {
            get {
                return ResourceManager.GetString("ProdutoServices_ExcluirProduto_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product deleted successfully!.
        /// </summary>
        public static string ProdutoServices_ExcluirProduto_Success {
            get {
                return ResourceManager.GetString("ProdutoServices_ExcluirProduto_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProdutoViewModels_AttributeName_Descricao {
            get {
                return ResourceManager.GetString("ProdutoViewModels_AttributeName_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture.
        /// </summary>
        public static string ProdutoViewModels_AttributeName_Fabricante {
            get {
                return ResourceManager.GetString("ProdutoViewModels_AttributeName_Fabricante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product / Services.
        /// </summary>
        public static string ProdutoViewModels_AttributeName_NomeProduto {
            get {
                return ResourceManager.GetString("ProdutoViewModels_AttributeName_NomeProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string ProdutoViewModels_AttributeName_Referencia {
            get {
                return ResourceManager.GetString("ProdutoViewModels_AttributeName_Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string ProdutoViewModels_AttributeName_Valor {
            get {
                return ResourceManager.GetString("ProdutoViewModels_AttributeName_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language:.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Log in.
        /// </summary>
        public static string UsuarioController_HttpGet_Login_Action_ViewBagTitle {
            get {
                return ResourceManager.GetString("UsuarioController_HttpGet_Login_Action_ViewBagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string UsuarioService_CadastrarUsuario_Error {
            get {
                return ResourceManager.GetString("UsuarioService_CadastrarUsuario_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Registred successfully!.
        /// </summary>
        public static string UsuarioService_CadastrarUsuario_Success {
            get {
                return ResourceManager.GetString("UsuarioService_CadastrarUsuario_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string UsuarioService_GerarNovaSenha_Error {
            get {
                return ResourceManager.GetString("UsuarioService_GerarNovaSenha_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found!.
        /// </summary>
        public static string UsuarioService_GerarNovaSenha_NotFound {
            get {
                return ResourceManager.GetString("UsuarioService_GerarNovaSenha_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password generated successfully!.
        /// </summary>
        public static string UsuarioService_GerarNovaSenha_Success {
            get {
                return ResourceManager.GetString("UsuarioService_GerarNovaSenha_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred:.
        /// </summary>
        public static string UsuarioServices_EncontrarUsuarioPor_Error {
            get {
                return ResourceManager.GetString("UsuarioServices_EncontrarUsuarioPor_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found!.
        /// </summary>
        public static string UsuarioServices_EncontrarUsuarioPor_NotFound {
            get {
                return ResourceManager.GetString("UsuarioServices_EncontrarUsuarioPor_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User found!.
        /// </summary>
        public static string UsuarioServices_EncontrarUsuarioPor_Success {
            get {
                return ResourceManager.GetString("UsuarioServices_EncontrarUsuarioPor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string UsuarioViewModels_Attribute_Email {
            get {
                return ResourceManager.GetString("UsuarioViewModels_Attribute_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string UsuarioViewModels_Attribute_Lembrar {
            get {
                return ResourceManager.GetString("UsuarioViewModels_Attribute_Lembrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UsuarioViewModels_Attribute_Senha {
            get {
                return ResourceManager.GetString("UsuarioViewModels_Attribute_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string View_Anunciante_AnunciantePartialView_Botao_Cancelar {
            get {
                return ResourceManager.GetString("View_Anunciante_AnunciantePartialView_Botao_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string View_Anunciante_AnunciantePartialView_Botao_Salvar {
            get {
                return ResourceManager.GetString("View_Anunciante_AnunciantePartialView_Botao_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string View_Anunciante_Cadastro_Botao_Salvar {
            get {
                return ResourceManager.GetString("View_Anunciante_Cadastro_Botao_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising.
        /// </summary>
        public static string View_Anunciante_Detalhes_Tab_Anuncio {
            get {
                return ResourceManager.GetString("View_Anunciante_Detalhes_Tab_Anuncio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string View_Anunciante_Detalhes_Tab_Endereco {
            get {
                return ResourceManager.GetString("View_Anunciante_Detalhes_Tab_Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string View_Anunciante_Detalhes_Tab_Produto {
            get {
                return ResourceManager.GetString("View_Anunciante_Detalhes_Tab_Produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Seller.
        /// </summary>
        public static string View_Anunciante_ListaAnunciantePartialView_Botao_NovoAnunciante {
            get {
                return ResourceManager.GetString("View_Anunciante_ListaAnunciantePartialView_Botao_NovoAnunciante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string View_Anuncio_AnuncioAlterarPartialView_Botao_Cancelar {
            get {
                return ResourceManager.GetString("View_Anuncio_AnuncioAlterarPartialView_Botao_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string View_Anuncio_AnuncioAlterarPartialView_Botao_Salvar {
            get {
                return ResourceManager.GetString("View_Anuncio_AnuncioAlterarPartialView_Botao_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string View_Anuncio_AnuncioAlterarPartialView_Calendario_DtFim {
            get {
                return ResourceManager.GetString("View_Anuncio_AnuncioAlterarPartialView_Calendario_DtFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string View_Anuncio_AnuncioAlterarPartialView_Calendario_DtInicio {
            get {
                return ResourceManager.GetString("View_Anuncio_AnuncioAlterarPartialView_Calendario_DtInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string View_Anuncio_ListaAnuncioPartialView_Botao_Alterar {
            get {
                return ResourceManager.GetString("View_Anuncio_ListaAnuncioPartialView_Botao_Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Advertising.
        /// </summary>
        public static string View_Anuncio_ListaAnuncioPartialView_Botao_NovoAnuncio {
            get {
                return ResourceManager.GetString("View_Anuncio_ListaAnuncioPartialView_Botao_NovoAnuncio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string View_Anuncio_ListaAnuncioPartialView_Botao_Publicar {
            get {
                return ResourceManager.GetString("View_Anuncio_ListaAnuncioPartialView_Botao_Publicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string View_Endereco_EnderecoPartialView_Botao_Cancelar {
            get {
                return ResourceManager.GetString("View_Endereco_EnderecoPartialView_Botao_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string View_Endereco_EnderecoPartialView_Botao_Salvar {
            get {
                return ResourceManager.GetString("View_Endereco_EnderecoPartialView_Botao_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        public static string View_Endereco_ListaEnderecoPartialView_Botao_NovoEndereco {
            get {
                return ResourceManager.GetString("View_Endereco_ListaEnderecoPartialView_Botao_NovoEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string View_Layout_Cultura_Ingles {
            get {
                return ResourceManager.GetString("View_Layout_Cultura_Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string View_Layout_Cultura_Portugues {
            get {
                return ResourceManager.GetString("View_Layout_Cultura_Portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string View_LayoutNav_Cadastro {
            get {
                return ResourceManager.GetString("View_LayoutNav_Cadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string View_LayoutNav_Contato {
            get {
                return ResourceManager.GetString("View_LayoutNav_Contato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string View_LayoutNav_Home {
            get {
                return ResourceManager.GetString("View_LayoutNav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager .
        /// </summary>
        public static string View_LayoutNav_Painel {
            get {
                return ResourceManager.GetString("View_LayoutNav_Painel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string View_LayoutNav_Sobre {
            get {
                return ResourceManager.GetString("View_LayoutNav_Sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string View_Produto_ListaProdutoPartialView_Botao_NovoProduto {
            get {
                return ResourceManager.GetString("View_Produto_ListaProdutoPartialView_Botao_NovoProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string View_Produto_ProdutoPartialView_Botao_Cancelar {
            get {
                return ResourceManager.GetString("View_Produto_ProdutoPartialView_Botao_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string View_Produto_ProdutoPartialView_Botao_Salvar {
            get {
                return ResourceManager.GetString("View_Produto_ProdutoPartialView_Botao_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string View_Usuario_UsuarioLogin_Botao_Login {
            get {
                return ResourceManager.GetString("View_Usuario_UsuarioLogin_Botao_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to acess.
        /// </summary>
        public static string View_Usuario_UsuarioLogin_Slogan {
            get {
                return ResourceManager.GetString("View_Usuario_UsuarioLogin_Slogan", resourceCulture);
            }
        }
    }
}
